# coding: utf-8

"""
    Kill Bill

    Kill Bill is an open-source billing and payments platform  # noqa: E501

    OpenAPI spec version: 0.24.10
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import killbill
from killbill.models.catalog_validation_error import CatalogValidationError  # noqa: E501
from killbill.rest import ApiException


class TestCatalogValidationError(unittest.TestCase):
    """CatalogValidationError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCatalogValidationError(self):
        """Test CatalogValidationError"""
        # FIXME: construct object with mandatory attributes with example values
        # model = killbill.models.catalog_validation_error.CatalogValidationError()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
