# coding: utf-8

"""
    Kill Bill

    Kill Bill is an open-source billing and payments platform  # noqa: E501

    OpenAPI spec version: 0.24.10
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from killbill.configuration import Configuration


class CatalogValidation(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'catalog_validation_errors': 'list[CatalogValidationError]'
    }

    attribute_map = {
        'catalog_validation_errors': 'catalogValidationErrors'
    }

    def __init__(self, catalog_validation_errors=None, _configuration=None):  # noqa: E501
        """CatalogValidation - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._catalog_validation_errors = None
        self.discriminator = None

        if catalog_validation_errors is not None:
            self.catalog_validation_errors = catalog_validation_errors

    @property
    def catalog_validation_errors(self):
        """Gets the catalog_validation_errors of this CatalogValidation.  # noqa: E501


        :return: The catalog_validation_errors of this CatalogValidation.  # noqa: E501
        :rtype: list[CatalogValidationError]
        """
        return self._catalog_validation_errors

    @catalog_validation_errors.setter
    def catalog_validation_errors(self, catalog_validation_errors):
        """Sets the catalog_validation_errors of this CatalogValidation.


        :param catalog_validation_errors: The catalog_validation_errors of this CatalogValidation.  # noqa: E501
        :type: list[CatalogValidationError]
        """

        self._catalog_validation_errors = catalog_validation_errors

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CatalogValidation, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CatalogValidation):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CatalogValidation):
            return True

        return self.to_dict() != other.to_dict()
